### PR TITLE
Added phpunit to composer dev dependencies

### PR DESCRIPTION
**Pull request by ascii-soup**
I am keen to start contributing as I'm about to begin using this library for a project I'm working on.

I don't have phpunit installed globally and since it now supports being installed with composer, I've added it as a dev dependency to make it easier to run the tests in this project.

### CODE REVIEW

**Comment by clue** [comment]
Thanks for your PR @ascii-soup! :+1: 

I know this is a controversial change, but I honestly don't mind either way :) Do you happen to have an insight if a consensus has been reached in the broader PHP community?

Also, IF we are to add this, we should probably use a version which is compatible with 5.3+ through 7 and HHVM and also update our Travis script.

**Comment by ascii-soup** [comment]
Good point on compatibility, I guess we could pin to a lower version of phpunit.

As for the Travis script, I thought I'd changed it! But evidently not. I can tidy up both of these things today and add to the PR.

**Comment by clue** [comment]
Thanks for your quick reply and I'm looking forward to seeing your update :+1: 

> Good point on compatibility, I guess we could pin to a lower version of phpunit.

See also Composer's `composer.json`: https://github.com/composer/composer/blob/f2d606ae0c705907d8bfa1c6f884bced1255b827/composer.json#L38

**Comment by ascii-soup** [comment]
Right, think this is all OK now.

**Comment by clue** [comment]
This should probably be added to `require-dev` instead of `require`, otherwise LGTM :+1:

**Comment by ascii-soup** [comment]
D'oh. That's what I get for squeezing it in between other bits of work.
Will fix up tomorrow :)

**Comment by ascii-soup** [comment]
OK - sorry for the delay. Added to require-dev.

**Comment by clue** [comment]
Thanks for your PR @ascii-soup, let's get this in already :shipit: 

For the reference: The Travis build time went up from ~30s to ~50s due to this change. IMO this is acceptable :+1:

**Pull request merged**
